apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 2
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: kleinmannn/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: QWvWk6wTId+maxRU
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-14723-4586-pgsql-primary.servers.linodedb.net:5432/customer
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer